name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]  # 触发分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout
      uses: actions/checkout@v4

    # 登录Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 构建并推送镜像
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lock-management:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/lock-management:latest

    # 通过SSH部署到云服务器
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker stop lock-management || true
          docker rm lock-management || true
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/lock-management:latest || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/lock-management:latest
          docker run -d --name lock-management -p 5001:5001 ${{ secrets.DOCKERHUB_USERNAME }}/lock-management:latest