# 用于构建和部署 Vue3 项目到 GitHub Pages
name: 部署到 GitHub Pages

on:
  # 当推送到 master 分支时触发
  push:
    branches: ["master"]

  # 允许从 Actions 选项卡手动触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过正在运行的部署之间排队的运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 安装依赖
        run: npm install
        
      - name: 构建
        run: npm run build:prod
        
      - name: 设置 Pages
        uses: actions/configure-pages@v5
        
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        